import { test, expect } from '@playwright/test'
import { mockPathApi } from '../src/test/fixtures'

test.beforeEach(async ({ page }) => {
  const api = mockPathApi()
  await page.route(/\/api\/(?:paths|topics|notes)(?:\/|\?|$)/, async route => {
    const request = route.request()
    const response = api(request.url(), request.method(), request.postData() ?? '')
    await route.fulfill({ status: response.status, contentType: 'application/json', body: response.status === 204 ? undefined : JSON.stringify(response.body) })
  })
})

test('desktop dashboard supports creating, editing, and deleting a learning path', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1080 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'A little more understanding.' })).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(6)
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'New learning path', exact: true }).click()
  await page.getByLabel('Title').fill('Browser-tested path')
  await page.getByLabel('Description').fill('A deliberate place to learn.')
  await page.getByRole('button', { name: 'Create learning path', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser-tested path' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Browser-tested path' })).toBeVisible()
  await page.getByRole('button', { name: 'Actions for Browser-tested path' }).click()
  await page.getByRole('menuitem', { name: 'Edit learning path' }).click()
  await page.getByLabel('Title').fill('Updated browser path')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByRole('button', { name: 'Actions for Updated browser path' }).click()
  await page.getByRole('menuitem', { name: 'Delete learning path' }).click()
  await page.getByRole('button', { name: 'Delete path', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Updated browser path' })).toHaveCount(0)
})

test('mobile navigation, modal, and deep links fit the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('dialog').getByRole('link', { name: 'SQL & Databases' }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'SQL & Databases' })).toBeVisible()
  await page.reload()
  await expect(page.getByText('5 completed · 100%')).toBeVisible()
  await page.getByRole('button', { name: 'Edit learning path', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/dialog-mobile.png', fullPage: true, animations: 'disabled' })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('topics persist after refresh and update learning-path progress', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: /Python & FastAPI Open learning path/ }).click()
  await page.getByRole('button', { name: 'Add topic' }).click()
  await page.getByLabel('Title').fill('FastAPI routing')
  await page.getByRole('button', { name: 'Add topic', exact: true }).last().click()
  await expect(page.getByRole('link', { name: 'FastAPI routing' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Status for FastAPI routing' }).selectOption('COMPLETED')
  await expect(page.getByText('1 completed · 20%')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('link', { name: 'FastAPI routing' })).toBeVisible()
  await expect(page.getByText('1 completed · 20%')).toBeVisible()
  await page.screenshot({ path: 'test-results/topics-desktop.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('link', { name: 'FastAPI routing' }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'FastAPI routing' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Your first note starts here.' })).toBeVisible()
})

test('notes save, preview Markdown safely, and survive refresh', async ({ page }) => {
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await page.getByRole('textbox', { name: 'Note title' }).fill('Routing notes')
  await page.getByRole('textbox', { name: 'Note content' }).fill('## Important\n\n```js\nconst route = true\n```\n\n<script>alert(1)</script>\n\n[unsafe](javascript:alert(1))')
  await expect(page.getByRole('button', { name: 'Split View' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Write Only' }).click()
  await expect(page.getByRole('region', { name: 'Markdown preview' })).toBeHidden()
  await expect(page.getByRole('textbox', { name: 'Note content' })).toContainText('const route = true')
  await page.getByRole('button', { name: 'Preview Only' }).click()
  await expect(page.getByRole('textbox', { name: 'Note content' })).toBeHidden()
  await page.getByRole('button', { name: 'Split View' }).click()
  await expect(page.getByRole('region', { name: 'Markdown preview' }).getByRole('heading', { name: 'Important' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Markdown preview' }).locator('script')).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Markdown preview' }).locator('a[href^="javascript:"]')).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Markdown preview' }).locator('.hljs')).toHaveCount(1)
  await expect(page.getByText('Saved automatically', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'Note title' })).toHaveValue('Routing notes')
  await expect(page.getByRole('textbox', { name: 'Note content' })).toContainText('const route = true')
  await page.getByRole('textbox', { name: 'Note title' }).fill('Unsaved title')
  await page.getByRole('link', { name: 'Back to topic' }).click()
  await expect(page.getByRole('dialog', { name: 'Leave without saving?' })).toBeVisible()
  await page.getByRole('button', { name: 'Keep editing' }).click()
  await expect(page.getByRole('textbox', { name: 'Note title' })).toHaveValue('Unsaved title')
  await page.getByRole('link', { name: 'Back to topic' }).click()
  await page.getByRole('button', { name: 'Discard changes' }).click()
  await expect(page.getByRole('link', { name: /Routing notes/ })).toBeVisible()
})

test('plain text notes keep formatting literal and save multiple learning links', async ({ page }) => {
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await page.getByRole('radio', { name: 'Plain text' }).check()
  await page.getByRole('textbox', { name: 'Note title' }).fill('References')
  await page.getByRole('textbox', { name: 'Note content' }).fill('**Read literally**\nSecond line')
  const preview = page.getByRole('region', { name: 'Plain text preview' })
  await expect(preview).toContainText('**Read literally**')
  await expect(preview.locator('strong')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Bold' })).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Link title optional' }).fill('Repository')
  await page.getByRole('textbox', { name: 'URL' }).fill('https://github.com/example/repo')
  await page.getByRole('button', { name: 'Add link' }).click()
  await page.getByRole('textbox', { name: 'URL' }).fill('https://www.youtube.com/watch?v=abc')
  await page.getByRole('button', { name: 'Add link' }).click()
  await expect(page.getByRole('list').getByRole('link', { name: /Repository/ })).toHaveAttribute('target', '_blank')
  await expect(page.getByRole('list').getByRole('link', { name: /Repository/ })).toHaveAttribute('rel', 'noopener noreferrer')
  await page.getByRole('button', { name: 'Save note' }).click()
  await page.reload()
  await expect(page.getByRole('radio', { name: 'Plain text' })).toBeChecked()
  await expect(page.getByRole('list').getByRole('link')).toHaveCount(2)
  await expect(page.getByRole('textbox', { name: 'Note content' })).toContainText('**Read literally**')
  await page.getByRole('radio', { name: 'Markdown' }).check()
  await expect(page.getByRole('region', { name: 'Markdown preview' }).locator('strong')).toHaveText('Read literally')
  await page.getByRole('button', { name: 'Save note' }).click()
  await page.reload()
  await expect(page.getByRole('radio', { name: 'Markdown' })).toBeChecked()
})

test('autosave serializes newer edits and persists the latest draft', async ({ page }) => {
  let activePatches = 0
  let maximumConcurrentPatches = 0
  const submittedTitles: string[] = []
  await page.route(/\/api\/notes\/\d+$/, async route => {
    if (route.request().method() !== 'PATCH') { await route.fallback(); return }
    const body = JSON.parse(route.request().postData() ?? '{}')
    submittedTitles.push(body.title)
    activePatches += 1
    maximumConcurrentPatches = Math.max(maximumConcurrentPatches, activePatches)
    if (body.title === 'First autosave') await new Promise(resolve => setTimeout(resolve, 1500))
    await route.fallback()
    activePatches -= 1
  })
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  const title = page.getByRole('textbox', { name: 'Note title' })
  await title.fill('First autosave')
  await expect.poll(() => submittedTitles).toContain('First autosave')
  await expect(page.getByText(/Saving/)).toBeVisible()
  await title.fill('Latest autosave')
  await expect(page.getByText('Saved automatically')).toBeVisible()
  expect(maximumConcurrentPatches).toBe(1)
  expect(submittedTitles).toEqual(['First autosave', 'Latest autosave'])
  await page.reload()
  await expect(title).toHaveValue('Latest autosave')
})
