import { test, expect, type Page } from '@playwright/test'
import { mockPathApi } from '../src/test/fixtures'

async function showNotes(page: Page) {
  await page.getByRole('tab', { name: 'Notes' }).click()
}

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => sessionStorage.setItem('studyforge-e2e-auth', 'enabled'))
  const api = mockPathApi()
  await page.route(/\/api\/(?:paths|topics|notes)(?:\/|\?|$)/, async route => {
    const request = route.request()
    const response = api(request.url(), request.method(), request.postData() ?? '')
    await route.fulfill({ status: response.status, contentType: 'application/json', body: response.status === 204 ? undefined : JSON.stringify(response.body) })
  })
})

test('sign out returns the visitor to the account screen', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'A little more understanding.' })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible()
  if (await page.getByLabel('Email address').count()) {
    await expect(page.getByRole('button', { name: 'Continue with Google' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Continue with GitHub' })).toBeVisible()
  } else {
    await expect(page.getByText(/Supabase Auth isn’t configured yet/)).toBeVisible()
  }
})

test('desktop dashboard supports creating, editing, and deleting a learning path', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1080 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'A little more understanding.' })).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(6)
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'New learning path', exact: true }).click()
  await page.getByLabel('Title').fill('Browser-tested path')
  await page.getByLabel('Description').fill('A deliberate place to learn.')
  await page.getByRole('button', { name: 'Create learning path', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser-tested path' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Browser-tested path' })).toBeVisible()
  await page.getByRole('button', { name: 'Actions for Browser-tested path' }).click()
  await page.getByRole('menuitem', { name: 'Edit learning path' }).click()
  await page.getByLabel('Title').fill('Updated browser path')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByRole('button', { name: 'Actions for Updated browser path' }).click()
  await page.getByRole('menuitem', { name: 'Delete learning path' }).click()
  await page.getByRole('button', { name: 'Delete path', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Updated browser path' })).toHaveCount(0)
})

test('mobile navigation, modal, and deep links fit the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('dialog').getByRole('link', { name: 'SQL & Databases' }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'SQL & Databases' })).toBeVisible()
  await page.reload()
  await expect(page.getByText('5 completed · 100%')).toBeVisible()
  await page.getByRole('button', { name: 'Edit learning path', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/dialog-mobile.png', fullPage: true, animations: 'disabled' })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('topics persist after refresh and update learning-path progress', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: /Python & FastAPI Open learning path/ }).click()
  await page.getByRole('button', { name: 'Add topic' }).click()
  await page.getByLabel('Title').fill('FastAPI routing')
  await page.getByRole('button', { name: 'Add topic', exact: true }).last().click()
  await expect(page.getByRole('link', { name: 'FastAPI routing' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Status for FastAPI routing' }).selectOption('COMPLETED')
  await expect(page.getByText('1 completed · 20%')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('link', { name: 'FastAPI routing' })).toBeVisible()
  await expect(page.getByText('1 completed · 20%')).toBeVisible()
  await page.screenshot({ path: 'test-results/topics-desktop.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('link', { name: 'FastAPI routing' }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'FastAPI routing' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Your first note starts here.' })).toBeVisible()
})

test('notes save, preview Markdown safely, and survive refresh', async ({ page }) => {
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await showNotes(page)
  await page.getByRole('textbox', { name: 'Note title' }).fill('Routing notes')
  await page.getByRole('textbox', { name: 'Note content' }).fill('## Important\n\n```js\nconst route = true\n```\n\n<script>alert(1)</script>\n\n[unsafe](javascript:alert(1))')
  await expect(page.getByRole('button', { name: 'Split View' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Write Only' }).click()
  await expect(page.getByRole('region', { name: 'Markdown preview' })).toBeHidden()
  await expect(page.getByRole('textbox', { name: 'Note content' })).toContainText('const route = true')
  await page.getByRole('button', { name: 'Preview Only' }).click()
  await expect(page.getByRole('textbox', { name: 'Note content' })).toBeHidden()
  await page.getByRole('button', { name: 'Split View' }).click()
  await expect(page.getByRole('region', { name: 'Markdown preview' }).getByRole('heading', { name: 'Important' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Markdown preview' }).locator('script')).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Markdown preview' }).locator('a[href^="javascript:"]')).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Markdown preview' }).locator('.hljs')).toHaveCount(1)
  await expect(page.getByRole('region', { name: 'Markdown preview' }).getByText('js', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Copy code' }).click()
  await expect(page.getByRole('button', { name: 'Copied' })).toBeVisible()
  await expect(page.getByText('Saved automatically', { exact: true })).toBeVisible()
  await page.reload()
  await showNotes(page)
  await expect(page.getByRole('textbox', { name: 'Note title' })).toHaveValue('Routing notes')
  await expect(page.getByRole('textbox', { name: 'Note content' })).toContainText('const route = true')
  await page.getByRole('textbox', { name: 'Note title' }).fill('Unsaved title')
  await page.getByRole('link', { name: 'Back to topic' }).click()
  await expect(page.getByRole('dialog', { name: 'Leave without saving?' })).toBeVisible()
  await page.getByRole('button', { name: 'Keep editing' }).click()
  await expect(page.getByRole('textbox', { name: 'Note title' })).toHaveValue('Unsaved title')
  await page.getByRole('link', { name: 'Back to topic' }).click()
  await page.getByRole('button', { name: 'Discard changes' }).click()
  await expect(page.getByRole('link', { name: /Routing notes/ })).toBeVisible()
})

test('note image upload resets the form after the async request', async ({ page }) => {
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await expect(page.getByRole('tab', { name: 'All' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Note title' }).fill('Image notes')
  await page.getByRole('button', { name: 'Save note' }).click()
  await page.getByRole('button', { name: /Add Content/ }).click()
  await page.getByRole('menuitem', { name: 'Upload Image' }).click()
  const file = page.getByLabel('Image file')
  await file.setInputFiles({ name: 'diagram.png', mimeType: 'image/png', buffer: Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]) })
  await page.getByRole('button', { name: 'Upload image' }).click()
  await expect(page.getByRole('button', { name: 'View image: diagram.png' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Images 1/ })).toBeVisible()
  await expect(file).toHaveValue('')
  await expect(page.getByRole('alert')).toHaveCount(0)
})

test('pasting a screenshot uploads it and inserts an inline image in either editor mode', async ({ page }) => {
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await showNotes(page)
  await page.getByRole('radio', { name: 'Plain text' }).check()
  const editor = page.getByRole('textbox', { name: 'Note content' })
  await editor.fill('Before after')
  await editor.evaluate((field: HTMLTextAreaElement) => field.setSelectionRange(7, 7))
  await editor.evaluate((field: HTMLTextAreaElement) => {
    const clipboard = new DataTransfer()
    clipboard.items.add(new File([new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10])], 'diagram.png', { type: 'image/png' }))
    field.dispatchEvent(new ClipboardEvent('paste', { bubbles: true, clipboardData: clipboard }))
  })
  await expect(editor).toContainText('Before')
  await expect(editor.locator('img')).toHaveAttribute('src', /token=fresh/)
  await expect(editor).toContainText('after')
  const uploadedUrl = await editor.locator('img').getAttribute('src')
  expect(uploadedUrl).toBeTruthy()
  await editor.fill(`Before\n\n![diagram.png]\\([${uploadedUrl}](${uploadedUrl})\\)\n\nafter`)
  await expect(editor.locator('img')).toHaveAttribute('src', /token=fresh/)
  await expect(page.getByRole('region', { name: 'Plain text preview' }).locator('img')).toHaveAttribute('src', /token=fresh/)
  await editor.press('Control+End')
  await editor.pressSequentially(' updated')
  await expect(editor).toContainText('after updated')
  await expect(page.getByRole('region', { name: 'Plain text preview' }).getByRole('button', { name: 'View image: diagram.png' })).toBeVisible()
  await page.getByRole('tab', { name: /Resources/ }).click()
  await page.getByRole('button', { name: /Images 0/ }).click()
  await expect(page.getByText('No separately uploaded images yet.')).toBeVisible()
  await page.getByRole('tab', { name: 'All' }).click()
  await expect(page.locator('.note-all-content')).toContainText('after updated')
  await expect(page.locator('.note-all-content img')).toHaveAttribute('src', /token=fresh/)
  await expect(page.getByText('Saved automatically', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('.note-all-content img')).toHaveAttribute('src', /token=fresh/)
  await page.getByRole('tab', { name: 'Notes' }).click()
  await expect(page.getByRole('textbox', { name: 'Note content' }).locator('img')).toHaveAttribute('src', /token=fresh/)
})

test('pasted screenshots render inline in Markdown mode and can be enlarged', async ({ page }) => {
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await showNotes(page)
  const editor = page.getByRole('textbox', { name: 'Note content' })
  await editor.evaluate((field: HTMLTextAreaElement) => {
    const clipboard = new DataTransfer()
    clipboard.items.add(new File([new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10])], 'diagram.png', { type: 'image/png' }))
    field.dispatchEvent(new ClipboardEvent('paste', { bubbles: true, clipboardData: clipboard }))
  })
  const preview = page.getByRole('region', { name: 'Markdown preview' })
  const pastedImage = preview.getByRole('button', { name: 'View image: diagram.png' })
  await expect(pastedImage).toBeVisible()
  await pastedImage.click()
  await expect(page.getByRole('dialog', { name: 'diagram.png' })).toBeVisible()
})

test('pasted image preview escapes an unfinished code block at its insertion point', async ({ page }) => {
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await showNotes(page)
  await page.getByRole('radio', { name: 'Plain text' }).check()
  const editor = page.getByRole('textbox', { name: 'Note content' })
  await editor.fill('```java\nBefore after')
  await editor.evaluate((field: HTMLTextAreaElement) => field.setSelectionRange(15, 15))
  await editor.evaluate((field: HTMLTextAreaElement) => {
    const clipboard = new DataTransfer()
    clipboard.items.add(new File([new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10])], 'diagram.png', { type: 'image/png' }))
    field.dispatchEvent(new ClipboardEvent('paste', { bubbles: true, clipboardData: clipboard }))
  })

  await expect(editor.locator('img')).toHaveAttribute('src', /token=fresh/)
  const preview = page.getByRole('region', { name: 'Plain text preview' })
  await expect(preview.locator('.hljs')).toHaveCount(1)
  await expect(preview.getByRole('button', { name: 'View image: diagram.png' })).toBeVisible()
  await expect(preview).toContainText('after')
  await expect(preview).not.toContainText('![diagram.png]')
})

test('content tabs preserve drafts and Add Content reuses resource flows', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await expect(page.getByRole('tab', { name: 'All' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('button', { name: /Add Content/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: /Add Content/ }).click()
  await page.getByRole('menuitem', { name: 'Write Text' }).click()
  await expect(page.getByRole('tab', { name: 'Notes' })).toHaveAttribute('aria-selected', 'true')
  const editor = page.getByRole('textbox', { name: 'Note content' })
  await expect(editor).toBeFocused()
  await editor.fill('# A clear overview\n\nDraft survives tab changes.')
  await page.getByRole('tab', { name: 'All' }).click()
  await expect(page.getByRole('heading', { name: 'A clear overview' })).toBeVisible()
  await expect(page.getByText('Saved automatically', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Add Content/ }).click()
  await page.getByRole('menuitem', { name: 'Upload Image' }).click()
  const file = page.getByLabel('Image file')
  await file.setInputFiles({ name: 'diagram.png', mimeType: 'image/png', buffer: Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]) })
  await page.getByRole('button', { name: 'Upload image' }).click()
  await expect(page.getByRole('tab', { name: 'Resources' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('button', { name: /Images 1/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'View image: diagram.png' })).toBeVisible()
  await page.getByRole('button', { name: 'View image: diagram.png' }).click()
  const viewer = page.getByRole('dialog', { name: 'diagram.png' })
  await expect(viewer.getByRole('img', { name: 'diagram.png' })).toHaveAttribute('src', /token=fresh/)
  await expect(viewer.getByRole('link', { name: 'Download image' })).toHaveAttribute('href', /download=diagram.png/)
  await page.keyboard.press('Escape')
  await expect(viewer).toHaveCount(0)
  await page.getByRole('tab', { name: 'Notes' }).click()
  await expect(page.getByRole('region', { name: 'Markdown preview' }).locator('img')).toHaveCount(0)
  await page.getByRole('tab', { name: 'All' }).click()
  await expect(page.locator('.note-all-content img')).toHaveCount(0)
  await expect(page.locator('.note-all-images img')).toHaveCount(1)
  await expect(page.locator('.note-all-images img')).toHaveAttribute('src', /token=fresh/)
  await page.getByRole('tab', { name: 'Resources' }).click()
  await page.getByRole('button', { name: /All Resources/ }).click()
  await page.getByRole('button', { name: 'Add link' }).click()
  await page.getByRole('textbox', { name: 'Link title optional' }).fill('Reference')
  await page.getByRole('textbox', { name: 'URL' }).fill('https://example.com/guide')
  await page.locator('.note-link-form').getByRole('button', { name: 'Add link' }).click()
  await page.getByRole('button', { name: /Links 1/ }).click()
  await expect(page.getByRole('link', { name: /Reference/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Images 1' }).click()
  await page.getByRole('button', { name: 'Remove diagram.png' }).click()
  await expect(page.getByRole('img', { name: 'diagram.png' })).toHaveCount(0)
})

test('plain text notes keep formatting literal and save multiple learning links', async ({ page }) => {
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await showNotes(page)
  await page.getByRole('radio', { name: 'Plain text' }).check()
  await page.getByRole('textbox', { name: 'Note title' }).fill('References')
  await page.getByRole('textbox', { name: 'Note content' }).fill('**Read literally**\nSecond line')
  const preview = page.getByRole('region', { name: 'Plain text preview' })
  await expect(preview).toContainText('**Read literally**')
  await expect(preview.locator('strong')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Bold' })).toHaveCount(0)
  await page.getByRole('button', { name: /Add Content/ }).click()
  await page.getByRole('menuitem', { name: 'Add Link' }).click()
  await page.getByRole('textbox', { name: 'Link title optional' }).fill('Repository')
  await page.getByRole('textbox', { name: 'URL' }).fill('https://github.com/example/repo')
  await page.locator('.note-link-form').getByRole('button', { name: 'Add link' }).click()
  await page.getByRole('textbox', { name: 'URL' }).fill('https://www.youtube.com/watch?v=abc')
  await page.locator('.note-link-form').getByRole('button', { name: 'Add link' }).click()
  await page.getByRole('tab', { name: 'Resources' }).click()
  await expect(page.getByRole('list').getByRole('link', { name: /Repository/ })).toHaveAttribute('target', '_blank')
  await expect(page.getByRole('list').getByRole('link', { name: /Repository/ })).toHaveAttribute('rel', 'noopener noreferrer')
  await page.getByRole('button', { name: 'Save note' }).click()
  await page.reload()
  await showNotes(page)
  await expect(page.getByRole('radio', { name: 'Plain text' })).toBeChecked()
  await page.getByRole('tab', { name: 'Resources' }).click()
  await expect(page.getByRole('list').getByRole('link')).toHaveCount(2)
  await showNotes(page)
  await expect(page.getByRole('textbox', { name: 'Note content' })).toContainText('**Read literally**')
  await page.getByRole('radio', { name: 'Markdown' }).check()
  await expect(page.getByRole('region', { name: 'Markdown preview' }).locator('strong')).toHaveText('Read literally')
  await page.getByRole('button', { name: 'Save note' }).click()
  await page.reload()
  await showNotes(page)
  await expect(page.getByRole('radio', { name: 'Markdown' })).toBeChecked()
})

test('autosave serializes newer edits and persists the latest draft', async ({ page }) => {
  let activePatches = 0
  let maximumConcurrentPatches = 0
  const submittedTitles: string[] = []
  await page.route(/\/api\/notes\/\d+$/, async route => {
    if (route.request().method() !== 'PATCH') { await route.fallback(); return }
    const body = JSON.parse(route.request().postData() ?? '{}')
    submittedTitles.push(body.title)
    activePatches += 1
    maximumConcurrentPatches = Math.max(maximumConcurrentPatches, activePatches)
    if (body.title === 'First autosave') await new Promise(resolve => setTimeout(resolve, 1500))
    await route.fallback()
    activePatches -= 1
  })
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await showNotes(page)
  const title = page.getByRole('textbox', { name: 'Note title' })
  await title.fill('First autosave')
  await expect.poll(() => submittedTitles).toContain('First autosave')
  await expect(page.getByText(/Saving/)).toBeVisible()
  await title.fill('Latest autosave')
  await expect(page.getByText('Saved automatically')).toBeVisible()
  expect(maximumConcurrentPatches).toBe(1)
  expect(submittedTitles).toEqual(['First autosave', 'Latest autosave'])
  await page.reload()
  await expect(title).toHaveValue('Latest autosave')
})

test('optional Learning Check collapses and persists reflection fields', async ({ page }) => {
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await showNotes(page)
  const toggle = page.getByRole('button', { name: /Learning Check/ })
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await toggle.click()
  await page.getByRole('textbox', { name: 'Key takeaway' }).fill('Retries need idempotent writes.')
  await page.getByRole('textbox', { name: 'Question to revisit' }).fill('How should retry keys expire?')
  await page.getByRole('radio', { name: 'Need More Practice' }).check()
  await expect(page.getByText('Saved automatically')).toBeVisible()
  await toggle.click()
  await expect(page.getByRole('textbox', { name: 'Key takeaway' })).toBeHidden()
  await page.reload()
  await showNotes(page)
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await expect(page.getByRole('textbox', { name: 'Key takeaway' })).toHaveValue('Retries need idempotent writes.')
  await expect(page.getByRole('textbox', { name: 'Question to revisit' })).toHaveValue('How should retry keys expire?')
  await expect(page.getByRole('radio', { name: 'Need More Practice' })).toBeChecked()
})

test('note editor uses a single-column split layout on small screens', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await showNotes(page)
  await page.getByRole('textbox', { name: 'Note content' }).fill('# Mobile preview')
  const editorBox = await page.getByRole('region', { name: 'Markdown editor' }).boundingBox()
  const previewBox = await page.getByRole('region', { name: 'Markdown preview' }).boundingBox()
  expect(editorBox).not.toBeNull()
  expect(previewBox).not.toBeNull()
  expect(previewBox!.y).toBeGreaterThanOrEqual(editorBox!.y + editorBox!.height)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: /Learning Check/ }).click()
  const takeawayBox = await page.getByRole('textbox', { name: 'Key takeaway' }).boundingBox()
  const questionBox = await page.getByRole('textbox', { name: 'Question to revisit' }).boundingBox()
  expect(questionBox!.y).toBeGreaterThan(takeawayBox!.y)
})

test('code block insertion is available in plain text and preserves the selected language', async ({ page }) => {
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await showNotes(page)
  await page.getByRole('radio', { name: 'Plain text' }).check()
  const editor = page.getByRole('textbox', { name: 'Note content' })
  await editor.fill('print("hello")')
  await editor.evaluate((field: HTMLTextAreaElement) => field.setSelectionRange(0, field.value.length))
  await page.getByRole('button', { name: 'Add code block' }).click()
  await page.getByLabel('Code language').selectOption('python')
  await page.getByRole('button', { name: 'Insert block' }).click()
  await expect(editor).toHaveValue('```python\nprint("hello")\n```')
  const plainPreview = page.getByRole('region', { name: 'Plain text preview' })
  await expect(plainPreview.getByText('python', { exact: true })).toBeVisible()
  await expect(plainPreview.locator('.hljs')).toHaveCount(1)
  await expect(plainPreview.getByRole('button', { name: 'Copy code' })).toBeVisible()
  await expect(plainPreview).not.toContainText('```')
  await page.getByRole('radio', { name: 'Markdown' }).check()
  const preview = page.getByRole('region', { name: 'Markdown preview' })
  await expect(preview.getByText('python', { exact: true })).toBeVisible()
  await expect(preview.locator('.hljs')).toHaveCount(1)
  await expect(preview.getByRole('button', { name: 'Copy code' })).toBeVisible()
})

test('plain-text note cards render fenced code as a compact syntax-highlighted preview', async ({ page }) => {
  await page.goto('/paths/5/topics/501')
  await page.getByRole('button', { name: 'New note' }).click()
  await showNotes(page)
  await page.getByRole('radio', { name: 'Plain text' }).check()
  await page.getByRole('textbox', { name: 'Note title' }).fill('Java snippet')
  await page.getByRole('textbox', { name: 'Note content' }).fill('```java\npublic int main() {\n  return 42;\n}\n```')
  await expect(page.getByText('Saved automatically')).toBeVisible()
  await page.getByRole('link', { name: 'Back to topic' }).click()
  const card = page.getByRole('link', { name: /Java snippet/ })
  await expect(card.locator('.note-card-code-language')).toHaveText('java')
  await expect(card.locator('.note-card-preview .hljs')).not.toHaveCount(0)
  await expect(card.locator('.note-card-preview')).not.toContainText('```')
})

test('demo workspace seeds paths, topic progress, notes, links, and private sample images', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Add sample data' }).click()
  await expect(page.getByRole('button', { name: 'Sample workspace added' })).toBeVisible({ timeout: 30000 })
  await expect(page.getByRole('heading', { name: 'Your learning paths' })).toContainText('9')

  await page.getByRole('link', { name: 'Demo · Python for Data Analysis', exact: true }).last().click()
  await page.getByRole('link', { name: 'Load and inspect datasets' }).click()
  await page.getByRole('link', { name: /A reliable data workflow/ }).click()
  await expect(page.locator('.note-all-content img')).toHaveAttribute('src', /token=fresh/)
  await page.getByRole('tab', { name: 'Resources' }).click()
  await expect(page.getByRole('button', { name: /Images 0/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /Links 2/ })).toBeVisible()

  await page.goto('/')
  await page.getByRole('link', { name: 'Demo · Relational Database Design', exact: true }).last().click()
  await page.getByRole('link', { name: 'Indexes and query plans' }).click()
  await page.getByRole('link', { name: /Indexes narrow the search/ }).click()
  await page.getByRole('tab', { name: 'Resources' }).click()
  await expect(page.getByRole('button', { name: /Images 1/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'View image: btree-index.png' })).toBeVisible()
})
