import { test, expect } from '@playwright/test'
import { mockPathApi } from '../src/test/fixtures'

test.beforeEach(async ({ page }) => {
  const api = mockPathApi()
  await page.route(/\/api\/paths(?:\/|\?|$)/, async route => {
    const request = route.request()
    const response = api(request.url(), request.method(), request.postData() ?? '')
    await route.fulfill({ status: response.status, contentType: 'application/json', body: response.status === 204 ? undefined : JSON.stringify(response.body) })
  })
})

test('desktop dashboard supports creating, editing, and deleting a learning path', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1080 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'A little more understanding.' })).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(6)
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'New learning path', exact: true }).click()
  await page.getByLabel('Title').fill('Browser-tested path')
  await page.getByLabel('Description').fill('A deliberate place to learn.')
  await page.getByRole('button', { name: 'Create learning path', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser-tested path' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Browser-tested path' })).toBeVisible()
  await page.getByRole('button', { name: 'Actions for Browser-tested path' }).click()
  await page.getByRole('menuitem', { name: 'Edit learning path' }).click()
  await page.getByLabel('Title').fill('Updated browser path')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByRole('button', { name: 'Actions for Updated browser path' }).click()
  await page.getByRole('menuitem', { name: 'Delete learning path' }).click()
  await page.getByRole('button', { name: 'Delete path', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Updated browser path' })).toHaveCount(0)
})

test('mobile navigation, modal, and deep links fit the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('dialog').getByRole('link', { name: 'SQL & Databases' }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'SQL & Databases' })).toBeVisible()
  await page.reload()
  await expect(page.getByText('5 completed · 100%')).toBeVisible()
  await page.getByRole('button', { name: 'Edit learning path', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/dialog-mobile.png', fullPage: true, animations: 'disabled' })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
